load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

_BUILD = """
# generated by repos.bzl
load("@rules_pkg//:mappings.bzl", "pkg_files")

filegroup(
    name = "files",
    srcs = {files},
    visibility = ["//visibility:public"]
)
"""

def _baseq3_repo_impl(repo_ctx):
    for name, sha256 in repo_ctx.attr.files.items():
        repo_ctx.report_progress("Fetching {}: {}".format(repo_ctx.name, name))
        repo_ctx.download(
            url = [x.format(name) for x in repo_ctx.attr.urls],
            output = name,
            sha256 = sha256,
            executable = False,
        )

    repo_ctx.file("BUILD.bazel", _BUILD.format(name = repo_ctx.name, files = [name for name, sha256 in repo_ctx.attr.files.items()]))

baseq3_repo = repository_rule(
    implementation = _baseq3_repo_impl,
    attrs = {
        "urls": attr.string_list(),
        "files": attr.string_dict(),
    },
)

def _module_impl(bzlmod = False):
    http_archive(
        name = "ioquake3",
        build_file = "@//:ioquake3.BUILD",
        sha256 = "9983b43f2fa716bbf965a13e864573039e6bf7db3dbbd4bd02c2f91fea130c21",
        strip_prefix = "ioq3-415f950ad322b3a1c5b06a7018c5f9b881592b34",
        urls = ["https://github.com/ioquake/ioq3/archive/415f950ad322b3a1c5b06a7018c5f9b881592b34.zip"],
    )
    baseq3_repo(
        name = "baseq3_full",
        urls = [
            "https://github.com/nrempel/q3-server/raw/master/baseq3/{}",
            "http://game.pioneernet.ru/dl/q3/files/pk3/{}",
        ],
        files = {
            "pak0.pk3": "7ce8b3910620cd50a09e4f1100f426e8c6180f68895d589f80e6bd95af54bcae",
            "pak1.pk3": "d4ffd60b4b414c3419499e321b6f5c2e933cf082df85823ad2d6ae2f803e1682",
            "pak2.pk3": "ccae938a2f13a03b24902d675181d516a431699701ed88023a307f34b5bcd58c",
            "pak3.pk3": "d03c0a0e06b99f9ecca2be7389f57faed406e85f7c09b9c56afdfa53ba25e312",
            "pak4.pk3": "af5f6d5c82fe4440ae0bb660f0648d1fa1731a9e8305a9eb652aa243428697f1",
            "pak5.pk3": "69f87070ca7719e252a3ba97e6483f6663939c987ede550d1268d4d9a07b45bc",
            "pak6.pk3": "bb4f0ae2bf603b050fb665436d3178ce7c1c20360e67bacf7c14d93daff38daf",
            "pak7.pk3": "de6283ce23e3486a2622c5dbf73d3721a59f24debd380e90f43a97d952fea283",
            "pak8.pk3": "812c9e97f231e89cefede3848c6110b7bd34245093af6f22c2cacde3e6b15663",
        },
    )

repos_bzlmod = module_extension(implementation = _module_impl)
